import type { Hotel } from "./types"

export const hotels: Hotel[] = [
  {
    id: "1",
    name: "Grand Luxury Hotel",
    location: "Bandung",
    price: 1200000,
    rating: 4.5,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 120,
  },
  {
    id: "2",
    name: "Mountain View Resort",
    location: "Bandung",
    price: 1500000,
    rating: 4.8,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 85,
  },
  {
    id: "3",
    name: "City Center Hotel",
    location: "Jakarta",
    price: 900000,
    rating: 4.2,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 150,
  },
  {
    id: "4",
    name: "Beach Paradise Resort",
    location: "Bali",
    price: 2500000,
    rating: 4.9,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 200,
  },
  {
    id: "5",
    name: "Riverside Inn",
    location: "Yogyakarta",
    price: 750000,
    rating: 4.0,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 60,
  },
  {
    id: "6",
    name: "Skyline Apartments",
    location: "Surabaya",
    price: 1100000,
    rating: 4.3,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 100,
  },
  {
    id: "7",
    name: "Heritage Boutique Hotel",
    location: "Solo",
    price: 950000,
    rating: 4.6,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 40,
  },
  {
    id: "8",
    name: "Tropical Oasis Resort",
    location: "Lombok",
    price: 1800000,
    rating: 4.7,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 150,
  },
  {
    id: "9",
    name: "Business District Suites",
    location: "Jakarta",
    price: 1300000,
    rating: 4.4,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 180,
  },
  {
    id: "10",
    name: "Volcano View Lodge",
    location: "Yogyakarta",
    price: 1600000,
    rating: 4.8,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 70,
  },
  {
    id: "11",
    name: "Sunset Beach Bungalows",
    location: "Bali",
    price: 2200000,
    rating: 4.9,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 50,
  },
  {
    id: "12",
    name: "Urban Chic Hotel",
    location: "Bandung",
    price: 1050000,
    rating: 4.3,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 90,
  },
  {
    id: "13",
    name: "Rainforest Eco Lodge",
    location: "Sumatra",
    price: 1400000,
    rating: 4.6,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 30,
  },
  {
    id: "14",
    name: "Harbor View Hotel",
    location: "Makassar",
    price: 980000,
    rating: 4.2,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 110,
  },
  {
    id: "15",
    name: "Cultural Heritage Inn",
    location: "Yogyakarta",
    price: 850000,
    rating: 4.5,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 45,
  },
  {
    id: "16",
    name: "Skyscraper Suite Hotel",
    location: "Jakarta",
    price: 2800000,
    rating: 4.8,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 250,
  },
  {
    id: "17",
    name: "Beachfront Paradise Resort",
    location: "Bali",
    price: 3500000,
    rating: 5.0,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 300,
  },
  {
    id: "18",
    name: "Mountain Retreat Lodge",
    location: "Bandung",
    price: 1750000,
    rating: 4.7,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 80,
  },
  {
    id: "19",
    name: "Riverside Glamping Resort",
    location: "Bogor",
    price: 1200000,
    rating: 4.4,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 25,
  },
  {
    id: "20",
    name: "Historic City Center Hotel",
    location: "Semarang",
    price: 920000,
    rating: 4.1,
    image: "/placeholder.svg?height=200&width=300",
    rooms: 75,
  },
]

export const locations = [
  "Bandung",
  "Jakarta",
  "Bali",
  "Surabaya",
  "Yogyakarta",
  "Solo",
  "Lombok",
  "Sumatra",
  "Makassar",
  "Bogor",
  "Semarang",
]

