// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type DetailhotelDocumentDataSlicesSlice = DetailHotelSlice;

/**
 * Content for detail_hotel documents
 */
interface DetailhotelDocumentData {
  /**
   * Slice Zone field in *detail_hotel*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: detailhotel.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DetailhotelDocumentDataSlicesSlice> /**
   * Meta Title field in *detail_hotel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: detailhotel.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *detail_hotel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: detailhotel.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *detail_hotel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detailhotel.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * detail_hotel document from Prismic
 *
 * - **API ID**: `detailhotel`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DetailhotelDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DetailhotelDocumentData>,
    "detailhotel",
    Lang
  >;

type SearchIdDocumentDataSlicesSlice = SortBySlice;

/**
 * Content for search documents
 */
interface SearchIdDocumentData {
  /**
   * Slice Zone field in *search*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: search_id.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SearchIdDocumentDataSlicesSlice> /**
   * Meta Title field in *search*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: search_id.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *search*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: search_id.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *search*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: search_id.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * search document from Prismic
 *
 * - **API ID**: `search_id`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SearchIdDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SearchIdDocumentData>,
    "search_id",
    Lang
  >;

export type AllDocumentTypes = DetailhotelDocument | SearchIdDocument;

/**
 * Item in *DetailHotel → Default → Primary → images*
 */
export interface DetailHotelSliceDefaultPrimaryImagesItem {
  /**
   * placeholder_images field in *DetailHotel → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.images[].placeholder_images
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  placeholder_images: prismic.ImageField<never>;
}

/**
 * Item in *DetailHotel → Default → Primary → reviews*
 */
export interface DetailHotelSliceDefaultPrimaryReviewsItem {
  /**
   * name field in *DetailHotel → Default → Primary → reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.reviews[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * ratings field in *DetailHotel → Default → Primary → reviews*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.reviews[].ratings
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  ratings: prismic.NumberField;

  /**
   * description field in *DetailHotel → Default → Primary → reviews*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.reviews[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * id_photos_review field in *DetailHotel → Default → Primary → reviews*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.reviews[].id_photos_review
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  id_photos_review: prismic.NumberField;

  /**
   * tags field in *DetailHotel → Default → Primary → reviews*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.reviews[].tags
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tags: prismic.SelectField<
    "strategic" | "kids_friendly" | "friendly_staff" | "clean_room"
  >;
}

/**
 * Item in *DetailHotel → Default → Primary → facilities*
 */
export interface DetailHotelSliceDefaultPrimaryFacilitiesItem {
  /**
   * facilities_list field in *DetailHotel → Default → Primary → facilities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.facilities[].facilities_list
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  facilities_list: prismic.KeyTextField;
}

/**
 * Item in *DetailHotel → Default → Primary → nearby_area*
 */
export interface DetailHotelSliceDefaultPrimaryNearbyAreaItem {
  /**
   * address field in *DetailHotel → Default → Primary → nearby_area*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.nearby_area[].address
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  address: prismic.GeoPointField;

  /**
   * range field in *DetailHotel → Default → Primary → nearby_area*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.nearby_area[].range
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  range: prismic.KeyTextField;
}

/**
 * Item in *DetailHotel → Default → Primary → rooms*
 */
export interface DetailHotelSliceDefaultPrimaryRoomsItem {
  /**
   * id_rooms field in *DetailHotel → Default → Primary → rooms*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms[].id_rooms
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  id_rooms: prismic.NumberField;

  /**
   * free_cancel field in *DetailHotel → Default → Primary → rooms*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: detail_hotel.default.primary.rooms[].free_cancel
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  free_cancel: prismic.BooleanField;

  /**
   * free_breakfast field in *DetailHotel → Default → Primary → rooms*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: detail_hotel.default.primary.rooms[].free_breakfast
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  free_breakfast: prismic.BooleanField;

  /**
   * large_bed field in *DetailHotel → Default → Primary → rooms*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: detail_hotel.default.primary.rooms[].large_bed
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  large_bed: prismic.BooleanField;

  /**
   * wide_rooms field in *DetailHotel → Default → Primary → rooms*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms[].wide_rooms
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  wide_rooms: prismic.NumberField;

  /**
   * is_smoking field in *DetailHotel → Default → Primary → rooms*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: detail_hotel.default.primary.rooms[].is_smoking
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_smoking: prismic.BooleanField;

  /**
   * is_bathtube field in *DetailHotel → Default → Primary → rooms*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: detail_hotel.default.primary.rooms[].is_bathtube
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_bathtube: prismic.BooleanField;

  /**
   * is_refrigerator field in *DetailHotel → Default → Primary → rooms*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: detail_hotel.default.primary.rooms[].is_refrigerator
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_refrigerator: prismic.BooleanField;

  /**
   * about rooms field in *DetailHotel → Default → Primary → rooms*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms[].about_rooms
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_rooms: prismic.RichTextField;

  /**
   * amenities field in *DetailHotel → Default → Primary → rooms*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms[].amenities
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  amenities: prismic.RichTextField;

  /**
   * room Facilities field in *DetailHotel → Default → Primary → rooms*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms[].room_facilities
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  room_facilities: prismic.RichTextField;

  /**
   * basic Facilities field in *DetailHotel → Default → Primary → rooms*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms[].basic_facilities
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  basic_facilities: prismic.RichTextField;
}

/**
 * Item in *DetailHotel → Default → Primary → images_rooms*
 */
export interface DetailHotelSliceDefaultPrimaryImagesRoomsItem {
  /**
   * images_rooms_placeholder field in *DetailHotel → Default → Primary → images_rooms*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.images_rooms[].images_rooms_placeholder
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  images_rooms_placeholder: prismic.ImageField<never>;

  /**
   * id_images_placeholder field in *DetailHotel → Default → Primary → images_rooms*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.images_rooms[].id_images_placeholder
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  id_images_placeholder: prismic.NumberField;
}

/**
 * Item in *DetailHotel → Default → Primary → rooms_options*
 */
export interface DetailHotelSliceDefaultPrimaryRoomsOptionsItem {
  /**
   * id_room_options field in *DetailHotel → Default → Primary → rooms_options*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms_options[].id_room_options
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  id_room_options: prismic.NumberField;

  /**
   * title_room field in *DetailHotel → Default → Primary → rooms_options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms_options[].title_room
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_room: prismic.KeyTextField;

  /**
   * sub_title_room field in *DetailHotel → Default → Primary → rooms_options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms_options[].sub_title_room
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title_room: prismic.KeyTextField;

  /**
   * bed_count field in *DetailHotel → Default → Primary → rooms_options*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms_options[].bed_count
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  bed_count: prismic.NumberField;

  /**
   * bed_type field in *DetailHotel → Default → Primary → rooms_options*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms_options[].bed_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bed_type: prismic.SelectField<"king bed" | "twin bed">;

  /**
   * is_refund field in *DetailHotel → Default → Primary → rooms_options*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: detail_hotel.default.primary.rooms_options[].is_refund
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_refund: prismic.BooleanField;

  /**
   * guest_count field in *DetailHotel → Default → Primary → rooms_options*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms_options[].guest_count
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  guest_count: prismic.NumberField;

  /**
   * tax_percentage field in *DetailHotel → Default → Primary → rooms_options*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms_options[].tax_percentage
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  tax_percentage: prismic.NumberField;

  /**
   * best_price field in *DetailHotel → Default → Primary → rooms_options*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: detail_hotel.default.primary.rooms_options[].best_price
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  best_price: prismic.BooleanField;

  /**
   * price field in *DetailHotel → Default → Primary → rooms_options*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms_options[].price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;
}

/**
 * Item in *DetailHotel → Default → Primary → other_recomendation*
 */
export interface DetailHotelSliceDefaultPrimaryOtherRecomendationItem {
  /**
   * name field in *DetailHotel → Default → Primary → other_recomendation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.other_recomendation[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * rating field in *DetailHotel → Default → Primary → other_recomendation*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.other_recomendation[].rating
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  rating: prismic.NumberField;

  /**
   * rating_point field in *DetailHotel → Default → Primary → other_recomendation*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 8.8
   * - **API ID Path**: detail_hotel.default.primary.other_recomendation[].rating_point
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  rating_point: prismic.NumberField;

  /**
   * rating_k field in *DetailHotel → Default → Primary → other_recomendation*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 8,9K => 8900
   * - **API ID Path**: detail_hotel.default.primary.other_recomendation[].rating_k
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  rating_k: prismic.NumberField;

  /**
   * price field in *DetailHotel → Default → Primary → other_recomendation*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.other_recomendation[].price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * fee_price field in *DetailHotel → Default → Primary → other_recomendation*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.other_recomendation[].fee_price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  fee_price: prismic.NumberField;

  /**
   * location field in *DetailHotel → Default → Primary → other_recomendation*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.other_recomendation[].location
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  location: prismic.GeoPointField;
}

/**
 * Item in *DetailHotel → Default → Primary → policy_general*
 */
export interface DetailHotelSliceDefaultPrimaryPolicyGeneralItem {
  /**
   * check_in_check_out field in *DetailHotel → Default → Primary → policy_general*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.policy_general[].check_in_check_out
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  check_in_check_out: prismic.KeyTextField;

  /**
   * Deposit field in *DetailHotel → Default → Primary → policy_general*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.policy_general[].deposit
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  deposit: prismic.KeyTextField;

  /**
   * Early Check in field in *DetailHotel → Default → Primary → policy_general*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.policy_general[].early_check_in
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  early_check_in: prismic.KeyTextField;

  /**
   * Late Check out field in *DetailHotel → Default → Primary → policy_general*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.policy_general[].late_check_out
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  late_check_out: prismic.KeyTextField;

  /**
   * Extra Breakfast field in *DetailHotel → Default → Primary → policy_general*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.policy_general[].extra_breakfast
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  extra_breakfast: prismic.KeyTextField;

  /**
   * Breakfast field in *DetailHotel → Default → Primary → policy_general*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.policy_general[].breakfast
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  breakfast: prismic.KeyTextField;

  /**
   * Pets field in *DetailHotel → Default → Primary → policy_general*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.policy_general[].pets
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pets: prismic.KeyTextField;

  /**
   * Additional Policy field in *DetailHotel → Default → Primary → policy_general*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.policy_general[].additional_policy
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  additional_policy: prismic.KeyTextField;

  /**
   * Airport Transfer field in *DetailHotel → Default → Primary → policy_general*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.policy_general[].airport_transfer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  airport_transfer: prismic.KeyTextField;
}

/**
 * Item in *DetailHotel → Default → Primary → general_information*
 */
export interface DetailHotelSliceDefaultPrimaryGeneralInformationItem {
  /**
   * Popular Facilities field in *DetailHotel → Default → Primary → general_information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.general_information[].popular_facilities
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  popular_facilities: prismic.KeyTextField;

  /**
   * Check In Check Out Time field in *DetailHotel → Default → Primary → general_information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.general_information[].check_in_check_out_time
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  check_in_check_out_time: prismic.KeyTextField;

  /**
   * Distance to Downtown field in *DetailHotel → Default → Primary → general_information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.general_information[].distance_to_downtown
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  distance_to_downtown: prismic.KeyTextField;

  /**
   * Popular in the Area field in *DetailHotel → Default → Primary → general_information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.general_information[].popular_in_the_area
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  popular_in_the_area: prismic.KeyTextField;

  /**
   * Breakfast Availability field in *DetailHotel → Default → Primary → general_information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.general_information[].breakfast_availability
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  breakfast_availability: prismic.KeyTextField;

  /**
   * Available rooms field in *DetailHotel → Default → Primary → general_information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.general_information[].available_rooms
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  available_rooms: prismic.KeyTextField;

  /**
   * Number of floors field in *DetailHotel → Default → Primary → general_information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.general_information[].number_of_floors
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number_of_floors: prismic.KeyTextField;

  /**
   * Another facilities field in *DetailHotel → Default → Primary → general_information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.general_information[].another_facilities
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  another_facilities: prismic.KeyTextField;

  /**
   * Nearby point of interest field in *DetailHotel → Default → Primary → general_information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.general_information[].nearby_point_of_interest
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nearby_point_of_interest: prismic.KeyTextField;
}

/**
 * Item in *DetailHotel → Default → Primary → faq*
 */
export interface DetailHotelSliceDefaultPrimaryFaqItem {
  /**
   * avail_facility field in *DetailHotel → Default → Primary → faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.faq[].avail_facility
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  avail_facility: prismic.KeyTextField;

  /**
   * cost field in *DetailHotel → Default → Primary → faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.faq[].cost
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cost: prismic.KeyTextField;

  /**
   * check_in_check_out field in *DetailHotel → Default → Primary → faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.faq[].check_in_check_out
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  check_in_check_out: prismic.KeyTextField;

  /**
   * provide_breakfast field in *DetailHotel → Default → Primary → faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.faq[].provide_breakfast
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  provide_breakfast: prismic.KeyTextField;

  /**
   * type_rooms field in *DetailHotel → Default → Primary → faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.faq[].type_rooms
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type_rooms: prismic.KeyTextField;
}

/**
 * Item in *DetailHotel → Default → Primary → ratings_section*
 */
export interface DetailHotelSliceDefaultPrimaryRatingsSectionItem {
  /**
   * fantastic field in *DetailHotel → Default → Primary → ratings_section*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.ratings_section[].fantastic
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  fantastic: prismic.NumberField;

  /**
   * very_good field in *DetailHotel → Default → Primary → ratings_section*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.ratings_section[].very_good
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  very_good: prismic.NumberField;

  /**
   * satisfying field in *DetailHotel → Default → Primary → ratings_section*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.ratings_section[].satisfying
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  satisfying: prismic.NumberField;

  /**
   * average field in *DetailHotel → Default → Primary → ratings_section*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.ratings_section[].average
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  average: prismic.NumberField;

  /**
   * poor field in *DetailHotel → Default → Primary → ratings_section*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.ratings_section[].poor
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  poor: prismic.NumberField;

  /**
   * clean field in *DetailHotel → Default → Primary → ratings_section*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.ratings_section[].clean
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  clean: prismic.NumberField;

  /**
   * comfort field in *DetailHotel → Default → Primary → ratings_section*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.ratings_section[].comfort
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  comfort: prismic.NumberField;

  /**
   * meal field in *DetailHotel → Default → Primary → ratings_section*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.ratings_section[].meal
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  meal: prismic.NumberField;

  /**
   * location field in *DetailHotel → Default → Primary → ratings_section*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.ratings_section[].location
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  location: prismic.NumberField;

  /**
   * service field in *DetailHotel → Default → Primary → ratings_section*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.ratings_section[].service
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  service: prismic.NumberField;
}

/**
 * Item in *DetailHotel → Default → Primary → image_ratings*
 */
export interface DetailHotelSliceDefaultPrimaryImageRatingsItem {
  /**
   * id_photos field in *DetailHotel → Default → Primary → image_ratings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.image_ratings[].id_photos
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  id_photos: prismic.NumberField;

  /**
   * images_photos field in *DetailHotel → Default → Primary → image_ratings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.image_ratings[].images_photos
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  images_photos: prismic.ImageField<never>;
}

/**
 * Primary content in *DetailHotel → Default → Primary*
 */
export interface DetailHotelSliceDefaultPrimary {
  /**
   * images field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<DetailHotelSliceDefaultPrimaryImagesItem>
  >;

  /**
   * ratings field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.ratings
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ratings: prismic.KeyTextField;

  /**
   * type field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"hotel" | "apartment" | "villa">;

  /**
   * price field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * review_ratings field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.review_ratings
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  review_ratings: prismic.NumberField;

  /**
   * tags_guest field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.tags_guest
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tags_guest: prismic.KeyTextField;

  /**
   * reviews field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.reviews[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  reviews: prismic.GroupField<
    Simplify<DetailHotelSliceDefaultPrimaryReviewsItem>
  >;

  /**
   * facilities field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.facilities[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  facilities: prismic.GroupField<
    Simplify<DetailHotelSliceDefaultPrimaryFacilitiesItem>
  >;

  /**
   * desc_hotel field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.desc_hotel
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  desc_hotel: prismic.RichTextField;

  /**
   * nearby_area field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.nearby_area[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nearby_area: prismic.GroupField<
    Simplify<DetailHotelSliceDefaultPrimaryNearbyAreaItem>
  >;

  /**
   * rooms field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  rooms: prismic.GroupField<Simplify<DetailHotelSliceDefaultPrimaryRoomsItem>>;

  /**
   * images_rooms field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.images_rooms[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images_rooms: prismic.GroupField<
    Simplify<DetailHotelSliceDefaultPrimaryImagesRoomsItem>
  >;

  /**
   * rooms_options field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.rooms_options[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  rooms_options: prismic.GroupField<
    Simplify<DetailHotelSliceDefaultPrimaryRoomsOptionsItem>
  >;

  /**
   * other_recomendation field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.other_recomendation[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  other_recomendation: prismic.GroupField<
    Simplify<DetailHotelSliceDefaultPrimaryOtherRecomendationItem>
  >;

  /**
   * policy_general field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.policy_general[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  policy_general: prismic.GroupField<
    Simplify<DetailHotelSliceDefaultPrimaryPolicyGeneralItem>
  >;

  /**
   * general_information field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.general_information[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  general_information: prismic.GroupField<
    Simplify<DetailHotelSliceDefaultPrimaryGeneralInformationItem>
  >;

  /**
   * faq field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.faq[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faq: prismic.GroupField<Simplify<DetailHotelSliceDefaultPrimaryFaqItem>>;

  /**
   * ratings_section field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.ratings_section[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  ratings_section: prismic.GroupField<
    Simplify<DetailHotelSliceDefaultPrimaryRatingsSectionItem>
  >;

  /**
   * image_ratings field in *DetailHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_hotel.default.primary.image_ratings[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  image_ratings: prismic.GroupField<
    Simplify<DetailHotelSliceDefaultPrimaryImageRatingsItem>
  >;
}

/**
 * Default variation for DetailHotel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailHotelSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DetailHotelSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DetailHotel*
 */
type DetailHotelSliceVariation = DetailHotelSliceDefault;

/**
 * DetailHotel Shared Slice
 *
 * - **API ID**: `detail_hotel`
 * - **Description**: DetailHotel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailHotelSlice = prismic.SharedSlice<
  "detail_hotel",
  DetailHotelSliceVariation
>;

/**
 * Item in *ListHotel → Default → Primary → hotel_list*
 */
export interface SortBySliceDefaultPrimaryHotelListItem {
  /**
   * id_hotel field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].id_hotel
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  id_hotel: prismic.NumberField;

  /**
   * name field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * travel_rating field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].travel_rating
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  travel_rating: prismic.KeyTextField;

  /**
   * rating field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].rating
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  rating: prismic.NumberField;

  /**
   * tag field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * discount field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: sort_by.default.primary.hotel_list[].discount
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  discount: prismic.BooleanField;

  /**
   * price_ori field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].price_ori
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price_ori: prismic.NumberField;

  /**
   * price_discount field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].price_discount
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price_discount: prismic.NumberField;

  /**
   * travel_review_origin field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].travel_review_origin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  travel_review_origin: prismic.KeyTextField;

  /**
   * type field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"hotel" | "villa" | "apartment">;

  /**
   * Date available field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].date_available
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_available: prismic.DateField;

  /**
   * Room available field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].room_available
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  room_available: prismic.NumberField;

  /**
   * tax_fee field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].tax_fee
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  tax_fee: prismic.NumberField;

  /**
   * address field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * mean_review field in *ListHotel → Default → Primary → hotel_list*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[].mean_review
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  mean_review: prismic.NumberField;
}

/**
 * Item in *ListHotel → Default → Primary → images*
 */
export interface SortBySliceDefaultPrimaryImagesItem {
  /**
   * id_images_list field in *ListHotel → Default → Primary → images*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.images[].id_images_list
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  id_images_list: prismic.NumberField;

  /**
   * images field in *ListHotel → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.images[].images
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  images: prismic.ImageField<never>;
}

/**
 * Primary content in *ListHotel → Default → Primary*
 */
export interface SortBySliceDefaultPrimary {
  /**
   * hotel_list field in *ListHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.hotel_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  hotel_list: prismic.GroupField<
    Simplify<SortBySliceDefaultPrimaryHotelListItem>
  >;

  /**
   * images field in *ListHotel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sort_by.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<SortBySliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for ListHotel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SortBySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SortBySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ListHotel*
 */
type SortBySliceVariation = SortBySliceDefault;

/**
 * ListHotel Shared Slice
 *
 * - **API ID**: `sort_by`
 * - **Description**: SortBy
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SortBySlice = prismic.SharedSlice<"sort_by", SortBySliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DetailhotelDocument,
      DetailhotelDocumentData,
      DetailhotelDocumentDataSlicesSlice,
      SearchIdDocument,
      SearchIdDocumentData,
      SearchIdDocumentDataSlicesSlice,
      AllDocumentTypes,
      DetailHotelSlice,
      DetailHotelSliceDefaultPrimaryImagesItem,
      DetailHotelSliceDefaultPrimaryReviewsItem,
      DetailHotelSliceDefaultPrimaryFacilitiesItem,
      DetailHotelSliceDefaultPrimaryNearbyAreaItem,
      DetailHotelSliceDefaultPrimaryRoomsItem,
      DetailHotelSliceDefaultPrimaryImagesRoomsItem,
      DetailHotelSliceDefaultPrimaryRoomsOptionsItem,
      DetailHotelSliceDefaultPrimaryOtherRecomendationItem,
      DetailHotelSliceDefaultPrimaryPolicyGeneralItem,
      DetailHotelSliceDefaultPrimaryGeneralInformationItem,
      DetailHotelSliceDefaultPrimaryFaqItem,
      DetailHotelSliceDefaultPrimaryRatingsSectionItem,
      DetailHotelSliceDefaultPrimaryImageRatingsItem,
      DetailHotelSliceDefaultPrimary,
      DetailHotelSliceVariation,
      DetailHotelSliceDefault,
      SortBySlice,
      SortBySliceDefaultPrimaryHotelListItem,
      SortBySliceDefaultPrimaryImagesItem,
      SortBySliceDefaultPrimary,
      SortBySliceVariation,
      SortBySliceDefault,
    };
  }
}
