// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  detail_hotel: dynamic(() => import("./DetailHotel")),
  sort_by: dynamic(() => import("./ListHotel")),
};
